import {
  collection,
  query,
  where,
  getDocs,
  doc,
  getDoc,
  updateDoc,
  orderBy,
} from 'firebase/firestore';
import { db } from '../config/firebase';
import { Fee } from '../types';

// MercadoPago Checkout URL (generated by Cloud Function)
// The Cloud Function creates the payment preference and stores the paymentUrl in Firestore
export const getUserFees = async (userId: string): Promise<Fee[]> => {
  const q = query(
    collection(db, 'fees'),
    where('userId', '==', userId),
    orderBy('year', 'desc'),
    orderBy('month', 'desc')
  );
  const snap = await getDocs(q);
  return snap.docs.map((d) => ({ id: d.id, ...d.data() } as Fee));
};

export const getFeeById = async (feeId: string): Promise<Fee | null> => {
  const snap = await getDoc(doc(db, 'fees', feeId));
  return snap.exists() ? ({ id: snap.id, ...snap.data() } as Fee) : null;
};

export const getFeeStatusLabel = (status: Fee['status']): string => {
  switch (status) {
    case 'pending': return 'Pendiente';
    case 'paid': return 'Pagada';
    case 'overdue': return 'Vencida';
    case 'processing': return 'En proceso';
    default: return status;
  }
};

export const getMonthName = (month: number): string => {
  const months = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
  ];
  return months[month - 1] ?? '';
};

export const getDaysUntilDue = (dueDate: number): number => {
  const now = new Date();
  const due = new Date(dueDate);
  const diffTime = due.getTime() - now.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
};

// Called by webhook when MP confirms payment
export const markFeeAsPaid = async (feeId: string, mpPaymentId: string) => {
  await updateDoc(doc(db, 'fees', feeId), {
    status: 'paid',
    paidAt: Date.now(),
    mercadopagoPaymentId: mpPaymentId,
  });
};

/*
 * MERCADOPAGO INTEGRATION GUIDE
 * ==============================
 * The actual payment preference creation happens in a Firebase Cloud Function.
 * See functions/src/mercadopago.ts for the full implementation.
 *
 * Flow:
 *  1. Cloud Function (scheduled) runs on day 1 of each month
 *  2. Creates an MP preference for each active user
 *  3. Stores the preference ID + payment URL in Firestore (fees collection)
 *  4. Sends push notifications to users
 *  5. MP calls webhook when payment is confirmed → marks fee as paid
 */
